pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "libmavlinkconnect.example"
include(":app")
includeBuild("../node_modules/@react-native/gradle-plugin")
